<?php declare(strict_types=1);

/**
 * Copyright (C) Brian Faust
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cline\StronglyTypedId\Generators;

use Cline\StronglyTypedId\Contracts\IdGeneratorInterface;

/**
 * Prefixed ID Generator.
 *
 * Generates Stripe-style prefixed identifiers by combining a prefix with
 * any underlying ID generator. Creates IDs in the format "prefix_id" where
 * the ID portion is generated by the configured generator.
 *
 * Features:
 * - Stripe-style format (prefix_id)
 * - Configurable prefix and generator
 * - Composable with any IdGeneratorInterface implementation
 * - Maintains underlying generator characteristics
 *
 * @psalm-immutable
 *
 * @author Brian Faust <brian@cline.sh>
 *
 * @example
 * ```php
 * // Customer ID using UUIDv7
 * $generator = new PrefixedIdGenerator('cus', new UuidV7Generator());
 * $id = $generator->generate(); // "cus_01906e2c-8e16-7e90-a1c1-6e47e5e6e3a0"
 *
 * // Charge ID using NanoID
 * $generator = new PrefixedIdGenerator('ch', new NanoIdGenerator());
 * $id = $generator->generate(); // "ch_V1StGXR8_Z5jdHi6B-myT"
 *
 * // Account ID using Sqids
 * $generator = new PrefixedIdGenerator('acct', new SqidsGenerator());
 * $id = $generator->generate(); // "acct_4d9fND1xQ"
 * ```
 */
final readonly class PrefixedIdGenerator implements IdGeneratorInterface
{
    /**
     * Create a new prefixed ID generator.
     *
     * @param string               $prefix    The prefix to prepend (e.g., 'cus', 'ch', 'acct')
     * @param IdGeneratorInterface $generator The underlying ID generator
     */
    public function __construct(
        private string $prefix,
        private IdGeneratorInterface $generator,
    ) {}

    /**
     * Generate a new prefixed identifier.
     *
     * Combines the configured prefix with an ID from the underlying generator,
     * separated by an underscore to create Stripe-style identifiers.
     *
     * @return string A prefixed ID (e.g., "cus_01906e2c-8e16-7e90-a1c1-6e47e5e6e3a0")
     */
    public function generate(): string
    {
        return $this->prefix.'_'.$this->generator->generate();
    }
}
